# Generated by Django 4.2.17 on 2025-02-08 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_seller_options_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Poster',
        ),
    ]
